// Executive team members
const executives = [
    {
        first_name: "Reza",
        last_name: "Tabrizi",
        email: "reza.tabrizi@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2025,
        linkedin: "https://www.linkedin.com/in/raytabrizi/",
        position: "President",
        headshot: "/members/reza-tabrizi.webp",
    },
    {
        first_name: "Cesar",
        last_name: "Gamez",
        email: "cesar.gamez@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2025,
        linkedin: "https://www.linkedin.com/in/cesar-gamez-84448124a/",
        position: "Vice President of Internal Affairs",
        headshot: "/members/cesar-gamez.webp",
    },
    {
        first_name: "Mytri",
        last_name: "Nair",
        email: "mytri.nair@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/mytrinair/",
        position: "Vice President of Internal Affairs",
        headshot: "/members/mytri-nair.jpeg",
    },
    {
        first_name: "Briden",
        last_name: "Garcia",
        email: "briden.garcia@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2025,
        linkedin: "https://www.linkedin.com/in/bridengarcia/",
        position: "Vice President of External Affairs",
        headshot: "/members/briden-garcia.webp",
    },
    {
        first_name: "Prajeethreddy",
        last_name: "Bhuma",
        email: "prajeethreddy.bhuma@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/prajeethreddybhuma/",
        position: "Vice President of Growth",
        headshot: "/members/prajeethreddy-bhuma.webp",
    },
    {
        first_name: "Giridhar",
        last_name: "Nair",
        email: "giridhar.nair@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/giridhar-nair/",
        position: "Vice President of Finance",
        headshot: "/members/giridhar-nair.webp",
    },
    {
        first_name: "Doris",
        last_name: "Naderi",
        email: "doris.naderi@consultyourcommunity.org",
        major: "Biology",
        graduation_year: 2026,
        linkedin: "https://www.linkedin.com/in/doris-naderi-94b62025a/",
        position: "Vice President of Marketing",
        headshot: "/members/doris-naderi.webp",
    },
];

const senior_analysts = [
    {
        first_name: "Akshara",
        last_name: "Akella",
        email: "akshara.akella@consultyourcommunity.org",
        major: "Business Administration",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/akshara-akella/",
        headshot: "/members/akshara-akella.jpg",
    },
    {
        first_name: "Suhas",
        last_name: "Shivaraju",
        email: "suhas.shivaraju@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2026,
        linkedin: "https://www.linkedin.com/in/suhas-shivaraju/",
        headshot: "/members/suhas-shivaraju.jpeg",
    },
    {
        first_name: "Anvik",
        last_name: "Shah",
        email: "anvik.shah@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2026,
        linkedin: "https://www.linkedin.com/in/anvik-shah/",
        headshot: "/members/anvik-shah.jpeg",
    },
    {
        first_name: "Lakshmi",
        last_name: "Ganapaneni",
        email: "lakshmi.ganapaneni@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2026,
        linkedin: "https://www.linkedin.com/in/lakshmi-l-ganapaneni/",
        headshot: "/members/lakshmi-ganapaneni.jpeg",
    },
    {
        first_name: "Varsha",
        last_name: "Janumpally",
        email: "varsha.janumpally@consultyourcommunity.org",
        major: "Information Technology",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/varsha-janumpally/",
        headshot: "/members/varsha-janumpally.jpeg",
    },
    {
        first_name: "Vikrant",
        last_name: "Jeeva",
        email: "vikrant.jeeva@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/vikrantjeeva/",
        headshot: "/members/vikrant-jeeva.jpeg",
    },
    {
        first_name: "Unaiza",
        last_name: "Khakoo",
        email: "Unaiza.khakoo@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2026,
        linkedin: "https://www.linkedin.com/in/unaizakhakoo/",
        headshot: "/members/unaiza-khakoo.jpeg",
    },
];

// Junior analyst team members
const junior_analysts = [
    {
        first_name: "Sahishnu",
        last_name: "Sagiraju",
        email: "sahishnu.sagiraju@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2025,
        linkedin: "https://www.linkedin.com/in/sahishnu-sagiraju/",
        headshot: "/members/sahishnu-sagiraju.jpeg",
    },
    {
        first_name: "Arnay",
        last_name: "Majumdar",
        email: "arnay.majumdar@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2028,
        linkedin: "https://www.linkedin.com/in/arnay-majumdar/",
        headshot: "/members/arnay-majumdar.jpeg",
    },
    {
        first_name: "Arnav",
        last_name: "Prabhu",
        email: "Arnav.Prabhu@consultyourcommunity.org",
        major: "Business Analytics",
        graduation_year: 2026,
        linkedin: "https://www.linkedin.com/in/arnavprabhu/",
        headshot: "/members/arnav-prabhu.jpeg",
    },
    {
        first_name: "Kaustubh",
        last_name: "Annavarapu",
        email: "Kaustubh.Annavarapu@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/kaustubhannavarapu/",
        headshot: "/members/kaustubh-annavarapu.jpeg",
    },
    {
        first_name: "Sree Aatish",
        last_name: "Bommisetty",
        email: "sbommisetty.bommisetty@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2026,
        linkedin: "https://www.linkedin.com/in/aatishbommisetty/",
        headshot: "/members/sreeatish-bommisetty.jpeg",
    },
    {
        first_name: "Aashna",
        last_name: "Pathi",
        email: "aashna.pathi@consultyourcommunity.org",
        major: "Biology",
        graduation_year: 2025,
        linkedin: "https://www.linkedin.com/in/aashna-pathi/",
        headshot: "/members/aashna-pathi.jpeg",
    },
    {
        first_name: "Jeslin",
        last_name: "Mathew",
        email: "jeslin.mathew@consultyourcommunity.org",
        major: "Supply Chain Management",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/jeslinlizmathew/",
        headshot: "/members/jeslin-matthew.jpeg",
    },
    {
        first_name: "Ayaan",
        last_name: "Mohammed",
        email: "ayaan.mohammed@consultyourcommunity.org",
        major: "Information Technology",
        graduation_year: 2028,
        linkedin: "https://www.linkedin.com/in/ayaanmohammed1/",
        headshot: "/members/ayaan-mohammed.jpeg",
    },
    {
        first_name: "Kushagra",
        last_name: "Bharti",
        email: "kushagra.bharti@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/kushagra-bharti/",
        headshot: "/members/kushagra-bharti.jpeg",
    },
    {
        first_name: "Mohammad Ammar",
        last_name: "Salman",
        email: "mohammadammar.salman@consultyourcommunity.org",
        major: "Information Technology",
        graduation_year: 2028,
        linkedin: "https://www.linkedin.com/in/ammarsalmanm/",
        headshot: "/members/mohammadammar-salman.jpeg",
    },
    {
        first_name: "Rushil",
        last_name: "Kannery",
        email: "rushil.kannery@consultyourcommunity.org",
        major: "Finance",
        graduation_year: 2026,
        linkedin: "https://www.linkedin.com/in/rushilkannery/",
        headshot: "/members/rushil-kannery.jpg",
    },
    {
        first_name: "Vidyut",
        last_name: "Tadepalli",
        email: "vidyut.tadepalli@consultyourcommunity.org",
        major: "Business Administration",
        graduation_year: 2028,
        linkedin: "https://www.linkedin.com/in/vidtadepalli/",
        position: "Junior Analyst - Agape Resources",
        headshot: "/members/vidyut-tadepalli.jpeg",
    },
    {
        first_name: "Anas",
        last_name: "Hassan",
        email: "anas.hassan@consultyourcommunity.org",
        major: "Business Analytics",
        graduation_year: 2026,
        linkedin: "https://www.linkedin.com/in/anas-hassan/",
        headshot: "/members/anas-hassan.jpeg",
    },
    {
        first_name: "Anya",
        last_name: "Mijar",
        email: "anya.mijar@consultyourcommunity.org",
        major: "Supply Chain Management",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/anyamijar/",
        headshot: "/members/anya-mijar.jpeg",
    },
    {
        first_name: "Arin",
        last_name: "Sood",
        email: "arin.sood@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/arin-sood/",
        headshot: "/members/arin-sood.jpeg",
    },
    {
        first_name: "Santosh",
        last_name: "Anaparti",
        email: "santosh.anaparti@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/santosh-anaparti-5aabb2244/",
        headshot: "/members/santosh-anaparti.jpeg",
    },
    {
        first_name: "Isha",
        last_name: "Rao",
        email: "isha.rao@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2026,
        linkedin: "https://www.linkedin.com/in/isha-rao11/",
        headshot: "/members/isha-rao.jpeg",
    },
    {
        first_name: "Satwik",
        last_name: "Padhy",
        email: "satwik.padhy@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2028,
        linkedin: "https://www.linkedin.com/in/satwik-yash-padhy/",
        headshot: "/members/satwik-padhy.jpeg",
    },
    {
        first_name: "Emmanuel",
        last_name: "Fakunle",
        email: "emmanuel.fakunle@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2026,
        linkedin: "https://www.linkedin.com/in/emmanuel-fakunle2003/",
        headshot: "/members/emmanuel-fakunle.jpeg",
    },
    {
        first_name: "Omesh Reddy",
        last_name: "Sana",
        email: "omeshreddy.sana@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/omesh-reddy-sana/",
        headshot: "/members/omeshreddy-sana.jpeg",
    },
    {
        first_name: "Pranav",
        last_name: "Boyapati",
        email: "pranav.boyapati@consultyourcommunity.org",
        major: "Computer Science",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/pranav-boyapati/",
        headshot: "/members/pranav-boyapati.jpg",
    },
    {
        first_name: "Ashna",
        last_name: "Murali",
        email: "test@gmail.com",
        major: "Business",
        graduation_year: 2027,
        linkedin: "https://www.linkedin.com/in/",
        headshot: "/members/pranav-boyapati.jpg",
    },
];

export { executives, senior_analysts, junior_analysts };
